import mongoose from "mongoose";

/**
 * Inquiry / lead generated by a buyer for a supplier's listing.
 * `createdAt` / `updatedAt` come from timestamps.
 */
const inquirySchema = new mongoose.Schema(
  {
    buyerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    supplierId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    listingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Listing",
      required: true,
      index: true,
    },
    name: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 120,
    },
    email: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
      maxlength: 320,
    },
    phone: {
      type: String,
      required: true,
      trim: true,
      maxlength: 40,
    },
    message: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 5000,
    },
    status: {
      type: String,
      enum: ["pending", "responded", "closed"],
      default: "pending",
      index: true,
    },
    isFlagged: {
      type: Boolean,
      default: false,
    },
    replies: [
      {
        senderRole: {
          type: String,
          enum: ["buyer", "supplier"],
          required: true,
        },
        message: {
          type: String,
          required: true,
          trim: true,
        },
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  { timestamps: true }
);

inquirySchema.index({ supplierId: 1, createdAt: -1 });
inquirySchema.index({ buyerId: 1, createdAt: -1 });
inquirySchema.index({ listingId: 1, buyerId: 1 }, { unique: true });

export default mongoose.model("Inquiry", inquirySchema);
